kind: pipeline
name: default

steps:
- name: publish
  image: plugins/github-release
  settings:
    api_key: 
        from_secret: git-release-token
    files: README.md 
    title: kubeadm-${DRONE_TAG}
    note: README.md 
    base_url: https://github.com/fanux/kube
    when:
        event: tag
